import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const hero = await readFile(new URL('../components/client/HeroSection.tsx', import.meta.url), 'utf8')
const page = await readFile(new URL('../app/page.tsx', import.meta.url), 'utf8')
const card = await readFile(new URL('../components/ui/ProductCard.tsx', import.meta.url), 'utf8')
const showcase = await readFile(new URL('../components/home/HomeProductShowcase.tsx', import.meta.url), 'utf8')
const compatibility = await readFile(new URL('../components/home/CompatibilityPreview.tsx', import.meta.url), 'utf8')
const homeGuides = await readFile(new URL('../components/home/HomeGuides.tsx', import.meta.url), 'utf8')
const contextGrid = await readFile(new URL('../components/home/HeroContextGrid.tsx', import.meta.url), 'utf8')
const trustStrip = await readFile(new URL('../components/home/HomeTrustStrip.tsx', import.meta.url), 'utf8').catch((error) => {
  if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') return ''
  throw error
})
const navbar = await readFile(new URL('../components/client/Navbar.tsx', import.meta.url), 'utf8')
const footer = await readFile(new URL('../components/server/Footer.tsx', import.meta.url), 'utf8')

assert.equal(hero.includes('hero1.webp'), false, 'the legacy homepage photograph must be removed')
assert.match(hero, /HeroContextGrid/, 'the hero must use the context grid component')
assert.equal(hero.includes('animate-gradient-text'), false, 'the hero headline must not use a decorative word gradient')
assert.equal(hero.includes('const TRUST'), false, 'hero reassurance must live in the dedicated trust section, not the hero')
assert.equal(hero.includes('48°'), false, 'the hero must not render decorative coordinates')
assert.equal(hero.includes('home-link-line'), false, 'the hero must not render arbitrary decorative connection lines')
assert.match(hero, /hero-arrival/, 'the hero must use one orchestrated arrival sequence')
assert.match(hero, /aria-labelledby="hero-title"/, 'the hero must retain a labelled landmark')
assert.match(contextGrid, /<nav\s+aria-label="Choisir selon votre besoin"/, 'needs must be presented as compact navigation')
assert.equal(contextGrid.includes('frame-label'), false, 'needs navigation must avoid decorative mono labels')
assert.match(contextGrid, /px-4 py-4/, 'needs navigation must stay compact')
assert.match(contextGrid, /<Link[\s\S]*?h-full/, 'each context link must fill its grid cell regardless of label wrapping')
assert.match(page, /HomeProductShowcase/, 'the homepage must expose the product and compatibility composition')
assert.match(card, /bg-white/, 'product imagery must remain on a neutral white surface')
assert.equal(hero.includes('Testé en studio'), false, 'unverified trust claims must not be rendered')
assert.equal(hero.includes('Prix temps réel'), false, 'unverified freshness claims must not be rendered')
assert.match(card, /interface ProductCardProps\s*{[^}]*\bvariant\?:\s*(?:'default'\s*\|\s*'home-showcase'|'home-showcase'\s*\|\s*'default')/, 'the product card props must declare the homepage showcase variant')
assert.match(card, /variant\s*===\s*'home-showcase'[\s\S]{0,160}?['"]home-showcase-card['"]/, 'the product card must apply the dedicated home-showcase-card layout marker')
assert.match(card, /variant\s*===\s*'home-showcase'[\s\S]{0,160}?aspect-\[1\/1\]/, 'the product card must apply the near-square home-showcase geometry')
assert.match(card, /availableOfferCount\s*===\s*1\)\s*return\s*'1 offre en stock'/, 'the product card must explicitly label one available offer')
assert.match(card, /offerCount\s*===\s*1\)\s*return\s*'1 marchand'/, 'the product card must use the singular merchant label')
assert.match(showcase, /variant="home-showcase"/, 'the homepage showcase must use the home-showcase product card variant')
assert.match(showcase, /grid-cols-1[^"\n]*sm:grid-cols-3/, 'the product selection must stay readable as one column on narrow mobile screens')
assert.doesNotMatch(showcase, /lg:grid-cols-12/, 'the product and setup composition must not create a shared-height desktop row too early')
assert.match(showcase, /id="selection"/, 'the showcase must be the hero secondary action destination')
assert.match(showcase, /xl:grid[^"\n]*xl:grid-cols-\[minmax\(0,2fr\)_minmax\(0,\.9fr\)\]/, 'the products and setup preview must sit side by side only at xl')
assert.match(showcase, /xl:grid[\s\S]*min-w-0[\s\S]*min-w-0/, 'both desktop composition columns must be allowed to shrink')
assert.match(showcase, /Notre sélection/, 'the product selection must use non-personalized language')
assert.doesNotMatch(showcase, /Sélectionné pour vous/, 'the product selection must not imply personalisation')
assert.match(showcase, /href="\/categorie\/audio"[\s\S]{0,240}?Voir l’audio/, 'the section CTA must accurately name its audio destination')
assert.doesNotMatch(showcase, /Voir la sélection\s*→/, 'the section CTA must not append a default arrow')
assert.match(showcase, /product\.slug === 'shure-sm7b' \? 'choix' : undefined/, 'the editorial badge must target the explicitly selected product')
assert.match(showcase, /<CompatibilityPreview\s*\/>/, 'the compatibility preview must be independent from product cards')
assert.doesNotMatch(showcase, /CompatibilityPreview products=/, 'the compatibility preview must not duplicate showcased products')
assert.match(compatibility, /Source[\s\S]*Traitement[\s\S]*Restitution/, 'the setup path must read source, processing, then output in order')
assert.match(compatibility, /setupNodes/, 'the compatibility graph must expose generic setup stages')
assert.match(compatibility, /Traitement/, 'the compatibility path must label the processing stage')
assert.match(compatibility, /setup-connector/, 'the setup path must use anchored explanatory connectors')
assert.match(compatibility, /top-0 h-1\/2/, 'each setup connector must reach from the item boundary to its center anchor')
assert.match(compatibility, /top-1\/2/, 'each setup connector must reach from its center anchor to the next item boundary')
assert.doesNotMatch(compatibility, /space-y-3/, 'setup connectors must not end at the next item top gap')
assert.match(compatibility, /motion-safe:animate-pulse/, 'only setup connectors should carry ambient motion')
assert.match(compatibility, /motion-reduce:animate-none/, 'setup connector motion must stop when reduced motion is requested')
assert.match(compatibility, /Le configurateur relie/, 'the compatibility preview must explain the configurator value immediately')
assert.doesNotMatch(compatibility, /<Image/, 'the compatibility preview must not repeat product imagery')
assert.doesNotMatch(compatibility, /\bh-full\b|xl:min-h-\[/, 'the setup panel must not force the shared composition height')
assert.match(compatibility, /xl:p-5/, 'the setup panel must use a materially tighter xl rhythm beside the product selection')
assert.doesNotMatch(compatibility, /0\{index \+ 1\}/, 'the compatibility graph must not use dynamic numeric labels')
assert.doesNotMatch(contextGrid, /num:/, 'the hero context grid must not retain repeated numeric labels')
assert.doesNotMatch(card, /xl:aspect-\[4\/5\]/, 'homepage product cards must no longer use the tall 4/5 geometry')
assert.match(card, /xl:aspect-\[1\/1\]/, 'homepage product cards must use a less stretched near-square geometry')
assert.match(card, /home-showcase-card[\s\S]{0,160}?bg-white/, 'homepage product cards must keep one continuous neutral surface')
assert.match(card, /xl:!line-clamp-1/, 'the homepage title must harden its xl single-line clamp against global clamp order')
assert.match(homeGuides, /className="object-cover h-full w-full/, 'guide images must explicitly fill their media frame')
assert.match(homeGuides, /lg:h-full lg:aspect-auto/, 'the featured guide media must fill the stretched desktop link')
assert.doesNotMatch(homeGuides, /text-foreground\/(?:45|50)/, 'guide category and metadata must retain at least 60 percent contrast')
assert.doesNotMatch(homeGuides, /\bpriority\b/, 'below-the-fold guide imagery must not preload')
assert.match(homeGuides, /featuredGuide\.image \? <Image/, 'the featured guide must keep a no-image fallback')
assert.match(homeGuides, /guide\.image \? <Image/, 'secondary guides must keep a no-image fallback')
assert.match(trustStrip, /from 'lucide-react'/, 'the trust strip must use the existing Lucide icon set')
assert.equal((trustStrip.match(/title: '/g) ?? []).length, 4, 'the trust strip must contain exactly four concise proofs')
assert.equal(page.includes('<main'), false, 'the homepage must not nest the layout main landmark')
assert.doesNotMatch(trustStrip, /livraison offerte/i, 'the trust strip must not claim free delivery')
assert.doesNotMatch(navbar, /lg:top-5/, 'the homepage navbar must remain flush with the top of the viewport')
assert.match(navbar, /#f2ebdf/, 'the navbar must use the unified cream palette')
assert.match(navbar, /bg-\[#f2ebdf\]/, 'the mega menu must use the cream navigation palette')
assert.doesNotMatch(navbar, /label:\s*'Image & Lumière'/)
assert.doesNotMatch(navbar, /label:\s*'Streaming'/)
assert.match(navbar, /label:\s*'Microphones'/)
assert.match(navbar, /label:\s*'Interfaces'/)
assert.match(navbar, /label:\s*'Accessoires'/)
assert.match(navbar, /label:\s*'Monitoring'/)
assert.doesNotMatch(footer, /href:\s*'\/categorie\/video'/)
assert.doesNotMatch(footer, /href:\s*'\/categorie\/streaming'/)
assert.match(footer, /href:\s*'\/categorie\/audio'/)
assert.match(footer, /href:\s*'\/categorie\/cartes-son'/)

const globalCss = await readFile(new URL('../app/globals.css', import.meta.url), 'utf8')
assert.match(globalCss, /--home-ink:\s+#0[89]0[78]0[56]/, 'homepage ink must use the studio black token')
assert.match(globalCss, /--home-ivory:\s+#F[13]E[AE][DE][5F]/, 'homepage typography must use the ivory token')
assert.match(globalCss, /--home-gold:\s+#(?:D3A85F|C89B52)/, 'homepage accents must use the brass token')
assert.match(globalCss, /@keyframes hero-arrival/, 'the homepage must define one orchestrated hero arrival')
assert.match(globalCss, /\.hero-arrival[\s\S]*animation:/, 'the hero arrival must be implemented in CSS')
assert.match(globalCss, /@media \(prefers-reduced-motion: reduce\)[\s\S]*html\s*\{[\s\S]*scroll-behavior:\s*auto/, 'reduced motion must also disable smooth anchor scrolling')
assert.match(hero, /href="#selection"/, 'the hero secondary action must point to the mixed selection section')
assert.match(hero, /Voir les essentiels/, 'the hero secondary action must describe the section it opens')

assert.match(page, /focusrite-scarlett-2i2-4th-gen/, 'homepage selection must include scarlett 2i2')
assert.match(page, /shure-sm7b/, 'homepage selection must include shure sm7b')
assert.match(page, /beyerdynamic-dt-770-pro-80-ohm/, 'homepage selection must include dt 770 pro')
assert.doesNotMatch(page, /sony-zv-e10/, 'homepage selection must not include sony camera')
assert.doesNotMatch(page, /elgato-stream-deck-mk2/, 'homepage selection must not include stream deck')

assert.doesNotMatch(homeGuides, /setup-youtube-debutant-2026/, 'home guides must not include youtube video guide')
assert.match(homeGuides, /isPublicAudioGuide/, 'home guides must filter through isPublicAudioGuide')

console.log('homepage design contract: ok')
